### ISSUE TITLE
AZERTY option

### ISSUE THREAD

**Issue by VincentVancalbergh** [jconnop/teron#2]
Change:
Up = A
Left = Q

**Comment by jconnop** [comment]
@VincentVancalbergh For AZERTY wouldn't you want this?

Up = Z
Left = Q
Down = S
Right = D

i.e. same layout as WASD but using the AZERTY equivalent keys in those positions.

**Comment by VincentVancalbergh** [comment]
@jconnop RIGHT! Sorry, Up = Z, Not A

**Comment by jconnop** [comment]
![image](https://user-images.githubusercontent.com/375060/145382493-0efb1a74-073d-478f-9b57-e94f0a7da9a4.png)

Option added for AZERTY users :)

**Comment by VincentVancalbergh** [comment]
TY! First tried it after this change! Was starting to despair! :p
