### ISSUE TITLE
Ability info on intro screen

### ISSUE THREAD

**Issue by jconnop** [jconnop/teron#5]
Maybe in a popup instead of cluttering the intro too much.

https://www.reddit.com/r/classicwow/comments/rbat6v/teron_gorefiend_flash_game_remade_in_a_modern_web/hnnkf26/

https://www.reddit.com/r/classicwow/comments/rbat6v/teron_gorefiend_flash_game_remade_in_a_modern_web/hnod6gy/

https://www.reddit.com/r/classicwowtbc/comments/rbaqup/teron_gorefiend_flash_game_remade_in_a_modern_web/hnno5mj/

**Comment by VincentVancalbergh** [comment]
Agreed. Learning as you go is terrible here. Some way to see what each ability does before starting the simulation.
